### ISSUE TITLE
Banshee crashes when playing videos

### ISSUE THREAD

**Issue by Carbenium** [arfbtwn/banshee#3]
I didn't investigate what causes the crash. I tried it with H264 MKV files and the native GStreamer backend.

**Suggestion:**
Since there are some pretty good cross-platform video players (e.g. VLC) I'd say the video playback feature could be dropped to simplify the codebase a bit.

**Comment by arfbtwn** [comment]
Some details on the crash would be handy, every video file or just MKVs?

Personally, since I don't use Banshee for video I agree with your suggestion and I explored doing it a while ago - the changes are quite far-reaching and mean an ABI break for plugins.

The other issue I thought about was our ability to contribute upstream and removing a major feature might hurt that. On balance, for now I think we'll leave it in.

**Comment by Carbenium** [comment]
Ok, curiosity didn't let to stop me ;)
It's actually GStreamer it self which doesn't like videos. I tried MKVs, MP4s (H264) and AVIs (MPEG-4).
Couldn't get it work on the commandline with playbin and Totem/XPlayer just fail with an unsupported format message.

Installed software versions:
Linux Mint 18.1
GStreamer 1.8.3 (including good, bad, ugly plugins)

Is there any kind of upstream maintainer at the moment?

**Comment by arfbtwn** [comment]
I'd check with your distro on how to sort out the gstreamer issue - it sounds like you've got all the right packages installed. I'll sure take a look, cheers

**Comment by arfbtwn** [comment]
This should definitely be a handled error case though, have you tested GNOME's master ​branch to confirm the crash? Would be good to file a bugzilla.gnome.org ticket too

**Comment by Carbenium** [comment]
For the reference: In my case it was the GStreamer VAAPI hardware acceleration which wasn't playing nicely. Removing it (packaged `gstreamer1.0-vaapi` on Ubuntu et al.) fixes a the playack problems.

We should show some kind of message if GStreamer isn't able to play the track.
